### PR TITLE
fix(filtersdropdown.tsx): fix filters dropdown header

### PR DESCRIPTION
**Pull request by migue1coel6odev**
## Motivation and Context

https://app.zenhub.com/workspaces/frontend-5d53e21db880a7648631a4f7/issues/carlsberggbs/dmbuddy-offshift/502

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by acaldas** [comment]
I don't understand this change doesn't the renderHeader prop already support this?

**Comment by migue1coel6odev** [comment]
the renderHeader from popover has only 1 arg, the visible one. I just keep it here to avoid breaking other places where renderHeader is used since I would need to rename it on the dropdown side to add the new argument @acaldas

**Comment by acaldas** [comment]
I see, in my view the props of the MultipleDropdown should be different, where the renderHeader also has the allSelected argument, so this would be treated as a breaking change. 

Otherwise we could call the new prop something like `renderAllSelectedHeader` to make it clearer.

**Comment by migue1coel6odev** [comment]
the this is that the renderHeader is extended from popover, which means that I can't have another prop named renderHeader on the dropdown side. 

imo the name `renderAllSelectedHeader` seems that is called only when `All` is selected which isn't the case :/

**Comment by acaldas** [comment]
> the this is that the renderHeader is extended from popover, which means that I can't have another prop named renderHeader on the dropdown side.

Yeah, we would need to override the Popover props.

> imo the name `renderAllSelectedHeader` seems that is called only when `All` is selected which isn't the case :/

I meant to say the renderAllSelectedHeader would be called only when All is selected. Falling back to the renderHeader if it is not defined. 
This way I think it would be clearer that this is a specific prop of the MultipleDropdown. Someone using the component for the first time wouldn't understand easily the difference between `renderHeader` and `renderCustomHeader`

**Comment by migue1coel6odev** [comment]
makes sense. just updated the PR:
https://github.com/Henrts/diana/pull/55/commits/7a776a4946137e6b6ca2c71554df691ab18c664a

**Pull request merged**
